name: Add User to Okta Group

on:
  workflow_dispatch:
    inputs:
      userEmail:
        description: 'User Email'
        required: true
      groupName:
        description: 'Group Name'
        required: true

jobs:
  add-user-to-group:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_API_TOKEN: ${{ secrets.OKTA_API_TOKEN }}
        run: python scripts/add_user_to_group.py ${{ github.event.inputs.userEmail }} ${{ github.event.inputs.groupName }}